# Generated by Django 3.0.3 on 2020-03-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200320_1404'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'inquiry_types',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Branch')),
                ('inquiry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inquiry.InquiryType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'db_table': 'inquires',
            },
        ),
    ]
