# Generated by Django 3.0.3 on 2020-03-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
        migrations.DeleteModel(
            name='InquiryType',
        ),
    ]
